// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-FHRB6nPl3--VuQDhHa1z6ylv3vd3qlc',
    appId: '1:922039274940:web:a2f7335237cd002424afb9',
    messagingSenderId: '922039274940',
    projectId: 'task-management-app-84623',
    authDomain: 'task-management-app-84623.firebaseapp.com',
    storageBucket: 'task-management-app-84623.appspot.com',
    measurementId: 'G-TTKK6KBQ6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVdpKW7sofirvNgzxDTuzmdhotvCue8uw',
    appId: '1:922039274940:android:f7d17e336f4308ba24afb9',
    messagingSenderId: '922039274940',
    projectId: 'task-management-app-84623',
    storageBucket: 'task-management-app-84623.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9NKBox5gRWdGBZlLCItb6_yOMdZJTpRI',
    appId: '1:922039274940:ios:eaec35b4f53310ce24afb9',
    messagingSenderId: '922039274940',
    projectId: 'task-management-app-84623',
    storageBucket: 'task-management-app-84623.appspot.com',
    iosBundleId: 'com.example.ropulvaFlutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9NKBox5gRWdGBZlLCItb6_yOMdZJTpRI',
    appId: '1:922039274940:ios:eaec35b4f53310ce24afb9',
    messagingSenderId: '922039274940',
    projectId: 'task-management-app-84623',
    storageBucket: 'task-management-app-84623.appspot.com',
    iosBundleId: 'com.example.ropulvaFlutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-FHRB6nPl3--VuQDhHa1z6ylv3vd3qlc',
    appId: '1:922039274940:web:00062d8b1ed9a49624afb9',
    messagingSenderId: '922039274940',
    projectId: 'task-management-app-84623',
    authDomain: 'task-management-app-84623.firebaseapp.com',
    storageBucket: 'task-management-app-84623.appspot.com',
    measurementId: 'G-TGNW8W4VGZ',
  );
}
